import { useState, useEffect } from 'react'
import type { PickerEntry } from '../../electron'
import { getLifecycleLog, type LifecycleEvent } from '../../lib/features'

interface VaultFile {
  folder: string
  name: string
  path: string
  size: number
  mtime: number
}

const FOLDER_DESCRIPTIONS: Record<string, string> = {
  imports: 'Drop files here to import them into corebooks',
  statements: 'Archived source documents and bank statements',
  receipts: 'Receipts linked to journal entries',
  exports: 'Files generated by corebooks (exports, reports)',
}

const IMPORTABLE_EXTS = new Set(['.csv', '.iif', '.json'])

function isImportable(name: string) {
  const ext = name.slice(name.lastIndexOf('.')).toLowerCase()
  return IMPORTABLE_EXTS.has(ext)
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
}

const VAULT_FOLDERS = ['imports', 'statements', 'receipts', 'exports']

export default function VaultTab() {
  const vault = window.electronAPI?.vault
  const [currentVault, setCurrentVault] = useState<PickerEntry | null>(null)
  const [filesOpen, setFilesOpen] = useState(false)
  const [files, setFiles] = useState<VaultFile[]>([])
  const [loadingFiles, setLoadingFiles] = useState(false)
  const [moveTarget, setMoveTarget] = useState<Record<string, string>>({})
  const [fileError, setFileError] = useState<string | null>(null)
  const [historyOpen, setHistoryOpen] = useState(false)
  const [log, setLog] = useState<LifecycleEvent[]>([])

  // Biometric state
  const [biometricAvailable, setBiometricAvailable] = useState<boolean>(false)
  const [biometricBusy, setBiometricBusy] = useState<boolean>(false)
  const [biometricError, setBiometricError] = useState<string | null>(null)

  // Close vault state
  const [closing, setClosing] = useState(false)

  // Identify the active vault by looking at the picker list and taking the most
  // recently opened entry. The active vault is always the one we have an API
  // connection to in this window, and the lifecycle code touches lastOpened on
  // open, so this is a safe proxy.
  useEffect(() => {
    if (!vault) return
    vault.list()
      .then((list) => {
        if (list.length === 0) { setCurrentVault(null); return }
        const sorted = [...list].sort((a, b) =>
          new Date(b.lastOpened).getTime() - new Date(a.lastOpened).getTime(),
        )
        setCurrentVault(sorted[0] ?? null)
      })
      .catch(() => setCurrentVault(null))
  }, [])

  useEffect(() => {
    if (!vault) return
    vault.isBiometricAvailable().then(setBiometricAvailable).catch(() => setBiometricAvailable(false))
  }, [])

  useEffect(() => {
    if (!filesOpen || !vault) return
    setLoadingFiles(true)
    vault.listVaultFiles()
      .then(setFiles)
      .catch(() => {})
      .finally(() => setLoadingFiles(false))
  }, [filesOpen])

  useEffect(() => {
    function refresh() {
      if (!filesOpen || !vault) return
      vault.listVaultFiles().then(setFiles).catch(() => {})
    }
    window.addEventListener('cb:vault-imports-changed', refresh)
    return () => window.removeEventListener('cb:vault-imports-changed', refresh)
  }, [filesOpen])

  useEffect(() => {
    if (historyOpen) setLog(getLifecycleLog())
  }, [historyOpen])

  if (!vault) {
    return (
      <div className="bg-surface border border-rim rounded-lg px-5 py-5 space-y-3">
        <h3 className="text-sm font-semibold text-chalk">Vaults are a desktop-only feature</h3>
        <p className="text-sm text-ash leading-relaxed">
          In the desktop app, every set of books lives in a <strong className="text-chalk">vault</strong> — a plain
          folder on your machine that you own and control. You pick which vault to open on every launch.
        </p>
        <p className="text-sm text-ash leading-relaxed">
          In web mode, corebooks connects to whichever database is configured via{' '}
          <code className="text-neon text-xs bg-raised px-1.5 py-0.5 rounded">DATABASE_URL</code>{' '}
          on the server. There is no vault picker because the database path is an infrastructure
          decision made by whoever deployed the server.
        </p>
        <p className="text-sm text-ash leading-relaxed">
          If you want local, transparent, file-system-based storage where you own every byte —
          the desktop app is what you want.
        </p>
      </div>
    )
  }

  async function handleMove(file: VaultFile) {
    const target = moveTarget[file.path]
    if (!target || target === file.folder) return
    setFileError(null)
    try {
      await vault!.moveFile(file.path, target)
      const updated = await vault!.listVaultFiles()
      setFiles(updated)
      setMoveTarget((prev) => { const next = { ...prev }; delete next[file.path]; return next })
    } catch (e) {
      setFileError(e instanceof Error ? e.message : 'Failed to move file')
    }
  }

  async function handleDelete(file: VaultFile) {
    if (!confirm(`Delete ${file.name}? This cannot be undone.`)) return
    setFileError(null)
    try {
      await vault!.deleteFile(file.path)
      setFiles((prev) => prev.filter((f) => f.path !== file.path))
    } catch (e) {
      setFileError(e instanceof Error ? e.message : 'Failed to delete file')
    }
  }

  function handleImportFile(file: VaultFile) {
    window.dispatchEvent(new CustomEvent('cb:vault-open-import', { detail: { path: file.path, name: file.name } }))
  }

  async function handleCloseVault() {
    if (!confirm('Close this vault and return to the vault picker? Unsaved changes are auto-saved as drafts.')) return
    setClosing(true)
    try {
      await vault!.close()
      // Main process unloads the vault and the renderer becomes effectively
      // detached from the API. A reload re-runs preload, which will see a null
      // apiBaseUrl and the VaultGate will show the picker.
      window.location.reload()
    } catch (e) {
      setClosing(false)
      alert(e instanceof Error ? e.message : 'Failed to close vault')
    }
  }

  async function handleEnableBiometric() {
    setBiometricBusy(true)
    setBiometricError(null)
    try {
      await vault!.enableBiometric()
    } catch (e) {
      setBiometricError(e instanceof Error ? e.message : 'Failed to enable biometric unlock')
    } finally {
      setBiometricBusy(false)
    }
  }

  async function handleDisableBiometric() {
    setBiometricBusy(true)
    setBiometricError(null)
    try {
      await vault!.disableBiometric()
    } catch (e) {
      setBiometricError(e instanceof Error ? e.message : 'Failed to disable biometric unlock')
    } finally {
      setBiometricBusy(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Vault identity */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-3">Vault</h3>
        <div className="bg-surface border border-rim rounded-lg px-5 py-4 space-y-2">
          <div className="flex items-center justify-between gap-3">
            <span className="text-sm text-chalk font-semibold">
              {currentVault?.displayName ?? 'Unknown vault'}
            </span>
            {currentVault && (
              <button
                onClick={() => void vault.showInExplorer(currentVault.path)}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer whitespace-nowrap"
              >
                Show in Finder
              </button>
            )}
          </div>
          {currentVault && (
            <div className="text-xs text-ash truncate font-mono">{currentVault.path}</div>
          )}
        </div>
      </div>

      {/* Close vault */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Close vault</h3>
        <p className="text-sm text-ash mb-3">
          Disconnect from this vault and return to the picker. Use this when you&apos;re done working,
          or to open a different vault.
        </p>
        <button
          onClick={() => void handleCloseVault()}
          disabled={closing}
          className="px-4 py-2 bg-raised border border-rim rounded text-sm text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {closing ? 'Closing…' : 'Close vault…'}
        </button>
      </div>

      {/* Biometric unlock */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Biometric unlock</h3>
        {biometricAvailable ? (
          <>
            <p className="text-sm text-ash mb-3">
              Allow your OS biometric (Touch ID, Windows Hello, etc.) to unlock this vault without
              typing your password. Your password is wrapped using OS-protected key material.
            </p>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => void handleEnableBiometric()}
                disabled={biometricBusy}
                className="px-3 py-1.5 bg-neon hover:bg-neon-dim text-void text-xs font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              >
                {biometricBusy ? 'Working…' : 'Enable biometric unlock'}
              </button>
              <button
                onClick={() => void handleDisableBiometric()}
                disabled={biometricBusy}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Disable
              </button>
            </div>
            {biometricError && (
              <p className="text-xs text-red-400 mt-2">{biometricError}</p>
            )}
          </>
        ) : (
          <p className="text-sm text-ash">
            Biometric unlock is not available on this device or OS configuration.
          </p>
        )}
      </div>

      {/* Vault password — placeholder for a future task */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Vault password</h3>
        <p className="text-sm text-ash">
          Your vault is encrypted with the password you chose when you created it. Changing the
          password and regenerating the recovery phrase from inside the app will return in a future
          release.
        </p>
      </div>

      {/* Vault contents */}
      <div>
        <button
          onClick={() => setFilesOpen((v) => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-chalk hover:text-neon transition-colors cursor-pointer"
        >
          <span>{filesOpen ? '▾' : '▸'}</span>
          Vault contents
        </button>

        {filesOpen && fileError && (
          <p className="mt-2 text-xs text-red-400">{fileError}</p>
        )}
        {filesOpen && (
          <div className="mt-3 bg-surface border border-rim rounded-lg divide-y divide-rim">
            {loadingFiles ? (
              <p className="px-5 py-4 text-sm text-ash">Loading…</p>
            ) : files.length === 0 ? (
              <p className="px-5 py-4 text-sm text-ash">No files in your vault yet.</p>
            ) : (
              VAULT_FOLDERS.map((folder) => {
                const folderFiles = files.filter((f) => f.folder === folder)
                if (folderFiles.length === 0) return null
                return (
                  <div key={folder}>
                    <div className="px-5 py-2 bg-raised/30 flex items-center gap-2">
                      <span className="text-xs font-semibold text-ash uppercase tracking-wide">{folder}/</span>
                      <span
                        className="text-xs text-ash/50 cursor-default"
                        title={FOLDER_DESCRIPTIONS[folder]}
                      >?</span>
                    </div>
                    {folderFiles.map((file) => (
                      <div key={file.path} className="flex items-center gap-3 px-5 py-2.5 border-t border-rim/30 hover:bg-raised/30">
                        <div className="flex-1 min-w-0">
                          <span className="text-sm text-chalk truncate block">{file.name}</span>
                          <span className="text-xs text-ash">{formatBytes(file.size)}</span>
                        </div>
                        <div className="flex items-center gap-2 shrink-0">
                          {isImportable(file.name) && (
                            <button
                              onClick={() => handleImportFile(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Import
                            </button>
                          )}
                          <select
                            value={moveTarget[file.path] ?? file.folder}
                            onChange={(e) => setMoveTarget((prev) => ({ ...prev, [file.path]: e.target.value }))}
                            className="text-xs bg-raised border border-rim rounded px-2 py-1 text-ash focus:outline-none focus:border-neon"
                          >
                            {VAULT_FOLDERS.map((f) => (
                              <option key={f} value={f}>{f}/</option>
                            ))}
                          </select>
                          {moveTarget[file.path] && moveTarget[file.path] !== file.folder && (
                            <button
                              onClick={() => void handleMove(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Move
                            </button>
                          )}
                          <button
                            onClick={() => void handleDelete(file)}
                            className="text-xs text-ash hover:text-red-400 transition-colors cursor-pointer"
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )
              })
            )}
          </div>
        )}
      </div>

      {/* Feature history */}
      <div>
        <button
          onClick={() => setHistoryOpen((v) => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-chalk hover:text-neon transition-colors cursor-pointer"
        >
          <span>{historyOpen ? '▾' : '▸'}</span>
          Feature history
        </button>
        {historyOpen && (
          <div className="mt-3 bg-surface border border-rim rounded-lg divide-y divide-rim">
            {log.length === 0 ? (
              <p className="px-5 py-4 text-sm text-ash">No feature changes recorded yet.</p>
            ) : (
              [...log].reverse().map((entry) => (
                <div key={`${entry.featureId}-${entry.event}-${entry.timestamp}`} className="flex items-center justify-between px-5 py-3">
                  <div>
                    <span className="text-sm text-chalk">{entry.featureName}</span>
                    <span className="text-xs text-ash ml-2">
                      {entry.event === 'enabled' ? 'Enabled'
                        : entry.event === 'hidden' ? 'Hidden'
                        : 'Re-enabled'}
                    </span>
                  </div>
                  <span className="text-xs text-ash font-mono">
                    {new Date(entry.timestamp).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'short',
                      day: 'numeric',
                    })}
                  </span>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  )
}
