import { useState, useEffect } from 'react'

interface VaultFile {
  folder: string
  name: string
  path: string
  size: number
  mtime: number
}

const FOLDER_DESCRIPTIONS: Record<string, string> = {
  imports: 'Drop files here to import them into corebooks',
  statements: 'Archived source documents and bank statements',
  receipts: 'Receipts linked to journal entries',
  exports: 'Files generated by corebooks (exports, reports)',
}

const IMPORTABLE_EXTS = new Set(['.csv', '.iif', '.json'])

function isImportable(name: string) {
  const ext = name.slice(name.lastIndexOf('.')).toLowerCase()
  return IMPORTABLE_EXTS.has(ext)
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
}

const VAULT_FOLDERS = ['imports', 'statements', 'receipts', 'exports']

function SafeStorageWarning() {
  const [available, setAvailable] = useState<boolean | null>(null)

  useEffect(() => {
    window.electronAPI?.vault.safeStorageAvailable()
      .then(setAvailable)
      .catch(() => setAvailable(false))
  }, [])

  if (available !== false) return null

  return (
    <div className="bg-amber-950/50 border border-amber-700 rounded-lg px-5 py-4 flex gap-3">
      <span className="text-amber-400 shrink-0 mt-0.5">⚠</span>
      <div>
        <p className="text-sm text-amber-300 font-medium">OS keychain unavailable</p>
        <p className="text-sm text-ash mt-1 leading-relaxed">
          The encryption key for your vault database is stored unprotected on this system.
          Install <code className="text-chalk bg-raised px-1 py-0.5 rounded text-xs">libsecret</code> and
          a keyring daemon (GNOME Keyring or KWallet) to enable OS-level encryption.
        </p>
      </div>
    </div>
  )
}

export default function VaultTab() {
  const vault = window.electronAPI?.vault
  const state = vault?.getState()
  const [name, setName] = useState(state?.vaultName ?? '')
  const [renaming, setRenaming] = useState(false)
  const [filesOpen, setFilesOpen] = useState(false)
  const [files, setFiles] = useState<VaultFile[]>([])
  const [loadingFiles, setLoadingFiles] = useState(false)
  const [moveTarget, setMoveTarget] = useState<Record<string, string>>({})

  useEffect(() => {
    if (!filesOpen || !vault) return
    setLoadingFiles(true)
    vault.listVaultFiles()
      .then(setFiles)
      .catch(() => {})
      .finally(() => setLoadingFiles(false))
  }, [filesOpen])

  useEffect(() => {
    function refresh() {
      if (!filesOpen || !vault) return
      vault.listVaultFiles().then(setFiles).catch(() => {})
    }
    window.addEventListener('cb:vault-imports-changed', refresh)
    return () => window.removeEventListener('cb:vault-imports-changed', refresh)
  }, [filesOpen])

  if (!vault || !state) {
    return (
      <div className="bg-surface border border-rim rounded-lg px-5 py-5 space-y-3">
        <h3 className="text-sm font-semibold text-chalk">Vaults are a desktop-only feature</h3>
        <p className="text-sm text-ash leading-relaxed">
          In the desktop app, every set of books lives in a <strong className="text-chalk">vault</strong> — a plain
          folder on your machine that you own and control. You pick which vault to open on every
          launch, and you can rename a vault directly from Settings (the folder renames on disk).
        </p>
        <p className="text-sm text-ash leading-relaxed">
          In web mode, corebooks connects to whichever database is configured via{' '}
          <code className="text-neon text-xs bg-raised px-1.5 py-0.5 rounded">DATABASE_URL</code>{' '}
          on the server. There is no vault picker because the database path is an infrastructure
          decision made by whoever deployed the server.
        </p>
        <p className="text-sm text-ash leading-relaxed">
          If you want local, transparent, file-system-based storage where you own every byte —
          the desktop app is what you want.
        </p>
      </div>
    )
  }

  async function handleRename() {
    if (!name.trim()) return
    setRenaming(true)
    try {
      await vault!.rename(name.trim())
    } catch (e) {
      console.error(e)
      setRenaming(false)
    }
  }

  async function handleMove(file: VaultFile) {
    const target = moveTarget[file.path]
    if (!target || target === file.folder) return
    await vault!.moveFile(file.path, target)
    const updated = await vault!.listVaultFiles()
    setFiles(updated)
    setMoveTarget((prev) => { const next = { ...prev }; delete next[file.path]; return next })
  }

  async function handleDelete(file: VaultFile) {
    if (!confirm(`Delete ${file.name}? This cannot be undone.`)) return
    await vault!.deleteFile(file.path)
    setFiles((prev) => prev.filter((f) => f.path !== file.path))
  }

  function handleImportFile(file: VaultFile) {
    window.dispatchEvent(new CustomEvent('cb:vault-open-import', { detail: { path: file.path, name: file.name } }))
  }

  return (
    <div className="space-y-6">
      {/* Vault name */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-3">Vault name</h3>
        <div className="flex gap-3">
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') void handleRename() }}
            className="flex-1 bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50"
          />
          <button
            onClick={() => void handleRename()}
            disabled={renaming || !name.trim() || name.trim() === state.vaultName}
            className="px-4 py-2 bg-neon hover:bg-neon-dim text-void text-sm font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {renaming ? 'Renaming…' : 'Rename'}
          </button>
        </div>
        {renaming ? (
          <p className="text-xs text-neon mt-2">Renaming folder on disk and restarting — the app will reopen in a moment.</p>
        ) : (
          <p className="text-xs text-ash mt-2">Renaming the vault renames the folder on disk and restarts the app.</p>
        )}
      </div>

      {/* Vault location */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Vault location</h3>
        <div className="flex items-center gap-3">
          <span className="flex-1 text-sm text-ash truncate font-mono">{state.vaultPath}</span>
          <button
            onClick={() => void vault.showInExplorer()}
            className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer whitespace-nowrap"
          >
            Show in Finder
          </button>
        </div>
      </div>

      {/* Switch vault */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Switch vault</h3>
        <p className="text-sm text-ash mb-3">Close the current vault and return to the vault picker.</p>
        <button
          onClick={() => void vault.relaunch()}
          className="px-4 py-2 bg-raised border border-rim rounded text-sm text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer"
        >
          Switch vault…
        </button>
      </div>

      {/* safeStorage warning */}
      <SafeStorageWarning />

      {/* Vault contents */}
      <div>
        <button
          onClick={() => setFilesOpen((v) => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-chalk hover:text-neon transition-colors cursor-pointer"
        >
          <span>{filesOpen ? '▾' : '▸'}</span>
          Vault contents
        </button>

        {filesOpen && (
          <div className="mt-3 bg-surface border border-rim rounded-lg divide-y divide-rim">
            {loadingFiles ? (
              <p className="px-5 py-4 text-sm text-ash">Loading…</p>
            ) : files.length === 0 ? (
              <p className="px-5 py-4 text-sm text-ash">No files in your vault yet.</p>
            ) : (
              VAULT_FOLDERS.map((folder) => {
                const folderFiles = files.filter((f) => f.folder === folder)
                if (folderFiles.length === 0) return null
                return (
                  <div key={folder}>
                    <div className="px-5 py-2 bg-raised/30 flex items-center gap-2">
                      <span className="text-xs font-semibold text-ash uppercase tracking-wide">{folder}/</span>
                      <span
                        className="text-xs text-ash/50 cursor-default"
                        title={FOLDER_DESCRIPTIONS[folder]}
                      >?</span>
                    </div>
                    {folderFiles.map((file) => (
                      <div key={file.path} className="flex items-center gap-3 px-5 py-2.5 border-t border-rim/30 hover:bg-raised/30">
                        <div className="flex-1 min-w-0">
                          <span className="text-sm text-chalk truncate block">{file.name}</span>
                          <span className="text-xs text-ash">{formatBytes(file.size)}</span>
                        </div>
                        <div className="flex items-center gap-2 shrink-0">
                          {isImportable(file.name) && (
                            <button
                              onClick={() => handleImportFile(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Import
                            </button>
                          )}
                          <select
                            value={moveTarget[file.path] ?? file.folder}
                            onChange={(e) => setMoveTarget((prev) => ({ ...prev, [file.path]: e.target.value }))}
                            className="text-xs bg-raised border border-rim rounded px-2 py-1 text-ash focus:outline-none focus:border-neon"
                          >
                            {VAULT_FOLDERS.map((f) => (
                              <option key={f} value={f}>{f}/</option>
                            ))}
                          </select>
                          {moveTarget[file.path] && moveTarget[file.path] !== file.folder && (
                            <button
                              onClick={() => void handleMove(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Move
                            </button>
                          )}
                          <button
                            onClick={() => void handleDelete(file)}
                            className="text-xs text-ash hover:text-red-400 transition-colors cursor-pointer"
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )
              })
            )}
          </div>
        )}
      </div>
    </div>
  )
}
