import { useState, useEffect } from 'react'
import { getLifecycleLog, type LifecycleEvent } from '../../lib/features'
import VaultPasswordSetup from '../../components/VaultPasswordSetup'
import VaultRecoverModal from '../../components/VaultRecoverModal'

interface VaultFile {
  folder: string
  name: string
  path: string
  size: number
  mtime: number
}

const FOLDER_DESCRIPTIONS: Record<string, string> = {
  imports: 'Drop files here to import them into corebooks',
  statements: 'Archived source documents and bank statements',
  receipts: 'Receipts linked to journal entries',
  exports: 'Files generated by corebooks (exports, reports)',
}

const IMPORTABLE_EXTS = new Set(['.csv', '.iif', '.json'])

function isImportable(name: string) {
  const ext = name.slice(name.lastIndexOf('.')).toLowerCase()
  return IMPORTABLE_EXTS.has(ext)
}

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
}

const VAULT_FOLDERS = ['imports', 'statements', 'receipts', 'exports']

function SafeStorageWarning() {
  const [available, setAvailable] = useState<boolean | null>(null)

  useEffect(() => {
    window.electronAPI?.vault.safeStorageAvailable()
      .then(setAvailable)
      .catch(() => setAvailable(false))
  }, [])

  if (available !== false) return null

  return (
    <div className="bg-amber-950/50 border border-amber-700 rounded-lg px-5 py-4 flex gap-3">
      <span className="text-amber-400 shrink-0 mt-0.5">⚠</span>
      <div>
        <p className="text-sm text-amber-300 font-medium">OS keychain unavailable</p>
        <p className="text-sm text-ash mt-1 leading-relaxed">
          The encryption key for your vault database is stored unprotected on this system.
          Install <code className="text-chalk bg-raised px-1 py-0.5 rounded text-xs">libsecret</code> and
          a keyring daemon (GNOME Keyring or KWallet) to enable OS-level encryption.
        </p>
      </div>
    </div>
  )
}

export default function VaultTab() {
  const vault = window.electronAPI?.vault
  const state = vault?.getState()
  const [name, setName] = useState(state?.vaultName ?? '')
  const [renaming, setRenaming] = useState(false)
  const [filesOpen, setFilesOpen] = useState(false)
  const [files, setFiles] = useState<VaultFile[]>([])
  const [loadingFiles, setLoadingFiles] = useState(false)
  const [moveTarget, setMoveTarget] = useState<Record<string, string>>({})
  const [fileError, setFileError] = useState<string | null>(null)
  const [historyOpen, setHistoryOpen] = useState(false)
  const [log, setLog] = useState<LifecycleEvent[]>([])
  const [encrypted, setEncrypted] = useState<boolean>(false)
  const [setupOpen, setSetupOpen] = useState(false)
  const [recoverOpen, setRecoverOpen] = useState(false)
  const [changeOpen, setChangeOpen] = useState(false)
  const [regenOpen, setRegenOpen] = useState(false)
  const [removeOpen, setRemoveOpen] = useState(false)
  const [regeneratedPhrase, setRegeneratedPhrase] = useState<string[] | null>(null)

  useEffect(() => {
    if (!vault) return
    vault.getEncryptionStatus().then((s) => setEncrypted(s.encrypted)).catch(() => {})
  }, [])

  function refreshStatus(): void {
    vault?.getEncryptionStatus().then((s) => setEncrypted(s.encrypted)).catch(() => {})
  }

  useEffect(() => {
    if (!filesOpen || !vault) return
    setLoadingFiles(true)
    vault.listVaultFiles()
      .then(setFiles)
      .catch(() => {})
      .finally(() => setLoadingFiles(false))
  }, [filesOpen])

  useEffect(() => {
    function refresh() {
      if (!filesOpen || !vault) return
      vault.listVaultFiles().then(setFiles).catch(() => {})
    }
    window.addEventListener('cb:vault-imports-changed', refresh)
    return () => window.removeEventListener('cb:vault-imports-changed', refresh)
  }, [filesOpen])

  useEffect(() => {
    if (historyOpen) setLog(getLifecycleLog())
  }, [historyOpen])

  if (!vault || !state) {
    return (
      <div className="bg-surface border border-rim rounded-lg px-5 py-5 space-y-3">
        <h3 className="text-sm font-semibold text-chalk">Vaults are a desktop-only feature</h3>
        <p className="text-sm text-ash leading-relaxed">
          In the desktop app, every set of books lives in a <strong className="text-chalk">vault</strong> — a plain
          folder on your machine that you own and control. You pick which vault to open on every
          launch, and you can rename a vault directly from Settings (the folder renames on disk).
        </p>
        <p className="text-sm text-ash leading-relaxed">
          In web mode, corebooks connects to whichever database is configured via{' '}
          <code className="text-neon text-xs bg-raised px-1.5 py-0.5 rounded">DATABASE_URL</code>{' '}
          on the server. There is no vault picker because the database path is an infrastructure
          decision made by whoever deployed the server.
        </p>
        <p className="text-sm text-ash leading-relaxed">
          If you want local, transparent, file-system-based storage where you own every byte —
          the desktop app is what you want.
        </p>
      </div>
    )
  }

  async function handleRename() {
    if (!name.trim()) return
    setRenaming(true)
    try {
      await vault!.rename(name.trim())
    } catch (e) {
      console.error(e)
      setRenaming(false)
    }
  }

  async function handleMove(file: VaultFile) {
    const target = moveTarget[file.path]
    if (!target || target === file.folder) return
    setFileError(null)
    try {
      await vault!.moveFile(file.path, target)
      const updated = await vault!.listVaultFiles()
      setFiles(updated)
      setMoveTarget((prev) => { const next = { ...prev }; delete next[file.path]; return next })
    } catch (e) {
      setFileError(e instanceof Error ? e.message : 'Failed to move file')
    }
  }

  async function handleDelete(file: VaultFile) {
    if (!confirm(`Delete ${file.name}? This cannot be undone.`)) return
    setFileError(null)
    try {
      await vault!.deleteFile(file.path)
      setFiles((prev) => prev.filter((f) => f.path !== file.path))
    } catch (e) {
      setFileError(e instanceof Error ? e.message : 'Failed to delete file')
    }
  }

  function handleImportFile(file: VaultFile) {
    window.dispatchEvent(new CustomEvent('cb:vault-open-import', { detail: { path: file.path, name: file.name } }))
  }

  return (
    <div className="space-y-6">
      {/* Vault name */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-3">Vault name</h3>
        <div className="flex gap-3">
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') void handleRename() }}
            className="flex-1 bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50"
          />
          <button
            onClick={() => void handleRename()}
            disabled={renaming || !name.trim() || name.trim() === state.vaultName}
            className="px-4 py-2 bg-neon hover:bg-neon-dim text-void text-sm font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {renaming ? 'Renaming…' : 'Rename'}
          </button>
        </div>
        {renaming ? (
          <p className="text-xs text-neon mt-2">Renaming folder on disk and restarting — the app will reopen in a moment.</p>
        ) : (
          <p className="text-xs text-ash mt-2">Renaming the vault renames the folder on disk and restarts the app.</p>
        )}
      </div>

      {/* Vault location */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Vault location</h3>
        <div className="flex items-center gap-3">
          <span className="flex-1 text-sm text-ash truncate font-mono">{state.vaultPath}</span>
          <button
            onClick={() => void vault.showInExplorer()}
            className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer whitespace-nowrap"
          >
            Show in Finder
          </button>
        </div>
      </div>

      {/* Switch vault */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Switch vault</h3>
        <p className="text-sm text-ash mb-3">Close the current vault and return to the vault picker.</p>
        <button
          onClick={() => void vault.relaunch()}
          className="px-4 py-2 bg-raised border border-rim rounded text-sm text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer"
        >
          Switch vault…
        </button>
      </div>

      {/* Vault password */}
      <div>
        <h3 className="text-sm font-semibold text-chalk mb-2">Vault password</h3>
        {encrypted ? (
          <>
            <p className="text-sm text-ash mb-3">
              Vault key is protected by your password. Full database encryption (SQLCipher) is
              pending a future update — for now, the password gates exports and protects the
              vault key inside <code className="text-xs bg-raised px-1.5 py-0.5 rounded">.corebooks</code>.
            </p>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => setChangeOpen(true)}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer"
              >
                Change password
              </button>
              <button
                onClick={() => setRegenOpen(true)}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer"
              >
                Regenerate recovery phrase
              </button>
              <button
                onClick={() => setRemoveOpen(true)}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-red-400 hover:border-red-500/50 transition-colors cursor-pointer"
              >
                Remove encryption
              </button>
            </div>
          </>
        ) : (
          <>
            <p className="text-sm text-ash mb-3">
              This vault is unencrypted — data is protected by your OS file permissions only.
              Set a password to enable strong encryption and require it on every open and export.
            </p>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={() => setSetupOpen(true)}
                className="px-3 py-1.5 bg-neon hover:bg-neon-dim text-void text-xs font-semibold rounded transition-colors cursor-pointer"
              >
                Set vault password
              </button>
              <button
                onClick={() => setRecoverOpen(true)}
                className="px-3 py-1.5 bg-raised border border-rim rounded text-xs text-ash hover:text-chalk hover:border-neon/50 transition-colors cursor-pointer"
              >
                Recover with 12-word phrase
              </button>
            </div>
          </>
        )}
      </div>

      {setupOpen && (
        <VaultPasswordSetup
          onComplete={() => { setSetupOpen(false); refreshStatus() }}
          onCancel={() => setSetupOpen(false)}
        />
      )}
      {recoverOpen && (
        <VaultRecoverModal
          onComplete={() => { setRecoverOpen(false); refreshStatus() }}
          onCancel={() => setRecoverOpen(false)}
        />
      )}
      {changeOpen && (
        <ChangePasswordModal
          onComplete={() => setChangeOpen(false)}
          onCancel={() => setChangeOpen(false)}
        />
      )}
      {regenOpen && (
        <RegenerateRecoveryModal
          onComplete={(phrase) => { setRegenOpen(false); setRegeneratedPhrase(phrase) }}
          onCancel={() => setRegenOpen(false)}
        />
      )}
      {regeneratedPhrase && (
        <DisplayPhraseModal phrase={regeneratedPhrase} onClose={() => setRegeneratedPhrase(null)} />
      )}
      {removeOpen && (
        <RemoveEncryptionModal
          onComplete={() => { setRemoveOpen(false); refreshStatus() }}
          onCancel={() => setRemoveOpen(false)}
        />
      )}

      {/* safeStorage warning */}
      <SafeStorageWarning />

      {/* Vault contents */}
      <div>
        <button
          onClick={() => setFilesOpen((v) => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-chalk hover:text-neon transition-colors cursor-pointer"
        >
          <span>{filesOpen ? '▾' : '▸'}</span>
          Vault contents
        </button>

        {filesOpen && fileError && (
          <p className="mt-2 text-xs text-red-400">{fileError}</p>
        )}
        {filesOpen && (
          <div className="mt-3 bg-surface border border-rim rounded-lg divide-y divide-rim">
            {loadingFiles ? (
              <p className="px-5 py-4 text-sm text-ash">Loading…</p>
            ) : files.length === 0 ? (
              <p className="px-5 py-4 text-sm text-ash">No files in your vault yet.</p>
            ) : (
              VAULT_FOLDERS.map((folder) => {
                const folderFiles = files.filter((f) => f.folder === folder)
                if (folderFiles.length === 0) return null
                return (
                  <div key={folder}>
                    <div className="px-5 py-2 bg-raised/30 flex items-center gap-2">
                      <span className="text-xs font-semibold text-ash uppercase tracking-wide">{folder}/</span>
                      <span
                        className="text-xs text-ash/50 cursor-default"
                        title={FOLDER_DESCRIPTIONS[folder]}
                      >?</span>
                    </div>
                    {folderFiles.map((file) => (
                      <div key={file.path} className="flex items-center gap-3 px-5 py-2.5 border-t border-rim/30 hover:bg-raised/30">
                        <div className="flex-1 min-w-0">
                          <span className="text-sm text-chalk truncate block">{file.name}</span>
                          <span className="text-xs text-ash">{formatBytes(file.size)}</span>
                        </div>
                        <div className="flex items-center gap-2 shrink-0">
                          {isImportable(file.name) && (
                            <button
                              onClick={() => handleImportFile(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Import
                            </button>
                          )}
                          <select
                            value={moveTarget[file.path] ?? file.folder}
                            onChange={(e) => setMoveTarget((prev) => ({ ...prev, [file.path]: e.target.value }))}
                            className="text-xs bg-raised border border-rim rounded px-2 py-1 text-ash focus:outline-none focus:border-neon"
                          >
                            {VAULT_FOLDERS.map((f) => (
                              <option key={f} value={f}>{f}/</option>
                            ))}
                          </select>
                          {moveTarget[file.path] && moveTarget[file.path] !== file.folder && (
                            <button
                              onClick={() => void handleMove(file)}
                              className="text-xs text-neon hover:bg-neon/10 px-2 py-1 rounded border border-neon/30 transition-colors cursor-pointer"
                            >
                              Move
                            </button>
                          )}
                          <button
                            onClick={() => void handleDelete(file)}
                            className="text-xs text-ash hover:text-red-400 transition-colors cursor-pointer"
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )
              })
            )}
          </div>
        )}
      </div>

      {/* Feature history */}
      <div>
        <button
          onClick={() => setHistoryOpen((v) => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-chalk hover:text-neon transition-colors cursor-pointer"
        >
          <span>{historyOpen ? '▾' : '▸'}</span>
          Feature history
        </button>
        {historyOpen && (
          <div className="mt-3 bg-surface border border-rim rounded-lg divide-y divide-rim">
            {log.length === 0 ? (
              <p className="px-5 py-4 text-sm text-ash">No feature changes recorded yet.</p>
            ) : (
              [...log].reverse().map((entry) => (
                <div key={`${entry.featureId}-${entry.event}-${entry.timestamp}`} className="flex items-center justify-between px-5 py-3">
                  <div>
                    <span className="text-sm text-chalk">{entry.featureName}</span>
                    <span className="text-xs text-ash ml-2">
                      {entry.event === 'enabled' ? 'Enabled'
                        : entry.event === 'hidden' ? 'Hidden'
                        : 'Re-enabled'}
                    </span>
                  </div>
                  <span className="text-xs text-ash font-mono">
                    {new Date(entry.timestamp).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'short',
                      day: 'numeric',
                    })}
                  </span>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  )
}

interface SimpleModalProps {
  onComplete: () => void
  onCancel: () => void
}

function ChangePasswordModal({ onComplete, onCancel }: SimpleModalProps) {
  const vault = window.electronAPI?.vault
  const [oldPassword, setOldPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const valid = newPassword.length >= 8 && newPassword === confirm && oldPassword.length > 0

  async function handleSubmit() {
    if (!vault || !valid) return
    setSubmitting(true); setError(null)
    try {
      const ok = await vault.verifyPassword(oldPassword)
      if (!ok) throw new Error('Current password is incorrect')
      await vault.changePassword(oldPassword, newPassword)
      onComplete()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to change password')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-void/80 backdrop-blur-sm flex items-center justify-center z-50 p-6">
      <div className="bg-surface border border-rim rounded-lg w-full max-w-md">
        <div className="px-6 py-4 border-b border-rim flex items-center justify-between">
          <h2 className="text-base font-semibold text-chalk">Change password</h2>
          <button onClick={onCancel} disabled={submitting} className="text-ash hover:text-chalk text-sm cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">Cancel</button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div>
            <label className="block text-xs font-semibold text-chalk mb-1">Current password</label>
            <input type="password" value={oldPassword} onChange={(e) => setOldPassword(e.target.value)} autoFocus autoComplete="current-password"
              className="w-full bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50" />
          </div>
          <div>
            <label className="block text-xs font-semibold text-chalk mb-1">New password (min. 8 characters)</label>
            <input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} autoComplete="new-password"
              className="w-full bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50" />
          </div>
          <div>
            <label className="block text-xs font-semibold text-chalk mb-1">Confirm new password</label>
            <input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} autoComplete="new-password"
              className="w-full bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50" />
          </div>
          {error && <p className="text-xs text-red-400">{error}</p>}
          <div className="flex justify-end">
            <button onClick={() => void handleSubmit()} disabled={!valid || submitting}
              className="px-4 py-2 bg-neon hover:bg-neon-dim text-void text-sm font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">
              {submitting ? 'Changing…' : 'Change password'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

interface RegenerateRecoveryModalProps {
  onComplete: (phrase: string[]) => void
  onCancel: () => void
}

function RegenerateRecoveryModal({ onComplete, onCancel }: RegenerateRecoveryModalProps) {
  const vault = window.electronAPI?.vault
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleSubmit() {
    if (!vault) return
    setSubmitting(true); setError(null)
    try {
      const ok = await vault.verifyPassword(password)
      if (!ok) throw new Error('Password is incorrect')
      const result = await vault.regenerateRecovery(password)
      onComplete(result.phraseWords)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to regenerate phrase')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-void/80 backdrop-blur-sm flex items-center justify-center z-50 p-6">
      <div className="bg-surface border border-rim rounded-lg w-full max-w-md">
        <div className="px-6 py-4 border-b border-rim flex items-center justify-between">
          <h2 className="text-base font-semibold text-chalk">Regenerate recovery phrase</h2>
          <button onClick={onCancel} disabled={submitting} className="text-ash hover:text-chalk text-sm cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">Cancel</button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div className="bg-amber-950/40 border border-amber-700 rounded-lg px-4 py-3">
            <p className="text-sm text-amber-300 font-medium">Warning</p>
            <p className="text-xs text-amber-200/80 mt-1">
              Your old 12-word phrase will stop working immediately. Make sure to write down the new
              phrase and destroy the old one.
            </p>
          </div>
          <div>
            <label className="block text-xs font-semibold text-chalk mb-1">Current password</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoFocus autoComplete="current-password"
              className="w-full bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50" />
          </div>
          {error && <p className="text-xs text-red-400">{error}</p>}
          <div className="flex justify-end">
            <button onClick={() => void handleSubmit()} disabled={!password || submitting}
              className="px-4 py-2 bg-neon hover:bg-neon-dim text-void text-sm font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">
              {submitting ? 'Generating…' : 'Generate new phrase'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

function DisplayPhraseModal({ phrase, onClose }: { phrase: string[]; onClose: () => void }) {
  return (
    <div className="fixed inset-0 bg-void/80 backdrop-blur-sm flex items-center justify-center z-50 p-6">
      <div className="bg-surface border border-rim rounded-lg w-full max-w-2xl">
        <div className="px-6 py-4 border-b border-rim">
          <h2 className="text-base font-semibold text-chalk">New recovery phrase</h2>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div className="bg-emerald-950/40 border border-emerald-700 rounded-lg px-4 py-3">
            <p className="text-sm text-emerald-300 font-medium">Write this on paper right now.</p>
            <p className="text-xs text-emerald-200/80 mt-1">Do not screenshot. Your old phrase no longer works.</p>
          </div>
          <div
            className="grid grid-cols-3 gap-2"
            onCopy={(e) => e.preventDefault()}
            onCut={(e) => e.preventDefault()}
            onDragStart={(e) => e.preventDefault()}
            style={{ userSelect: 'none' }}
          >
            {phrase.map((word, i) => (
              <div key={i} className="flex items-center gap-2 bg-raised border border-rim rounded px-3 py-2">
                <span className="text-xs text-ash font-mono w-5 text-right">{i + 1}.</span>
                <span className="text-sm text-chalk font-mono">{word}</span>
              </div>
            ))}
          </div>
          <div className="flex justify-end">
            <button onClick={onClose}
              className="px-4 py-2 bg-neon hover:bg-neon-dim text-void text-sm font-semibold rounded transition-colors cursor-pointer">
              I've written it down
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

function RemoveEncryptionModal({ onComplete, onCancel }: SimpleModalProps) {
  const vault = window.electronAPI?.vault
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleSubmit() {
    if (!vault || !password) return
    setSubmitting(true); setError(null)
    try {
      await vault.removeEncryption(password)
      onComplete()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to remove encryption')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-void/80 backdrop-blur-sm flex items-center justify-center z-50 p-6">
      <div className="bg-surface border border-rim rounded-lg w-full max-w-md">
        <div className="px-6 py-4 border-b border-rim flex items-center justify-between">
          <h2 className="text-base font-semibold text-chalk">Remove encryption</h2>
          <button onClick={onCancel} disabled={submitting} className="text-ash hover:text-chalk text-sm cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">Cancel</button>
        </div>
        <div className="px-6 py-6 space-y-4">
          <div className="bg-red-950/40 border border-red-700 rounded-lg px-4 py-3">
            <p className="text-sm text-red-300 font-medium">This removes password protection.</p>
            <p className="text-xs text-red-200/80 mt-1">
              The vault key wrap and recovery phrase are deleted from
              <code className="text-xs bg-raised px-1 py-0.5 rounded ml-1">.corebooks</code>.
              The vault is again protected only by OS file permissions.
            </p>
          </div>
          <div>
            <label className="block text-xs font-semibold text-chalk mb-1">Current password</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoFocus autoComplete="current-password"
              className="w-full bg-raised border border-rim rounded px-3 py-2 text-sm text-chalk focus:outline-none focus:border-neon/50" />
          </div>
          {error && <p className="text-xs text-red-400">{error}</p>}
          <div className="flex justify-end">
            <button onClick={() => void handleSubmit()} disabled={!password || submitting}
              className="px-4 py-2 bg-red-600 hover:bg-red-500 text-chalk text-sm font-semibold rounded transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed">
              {submitting ? 'Removing…' : 'Remove encryption'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
